import { ThemeId, themesResponseSchema, type ThemeCatalogItem, type ThemeDefinition, type ThemesResponse, type ThemeValidationIssue } from '@finapp/shared';

import { validateThemeAccessibility } from './validation';

const baseTypography = {
  fontSans: 'ibmPlexSans',
  fontMono: 'ibmPlexMono',
  fontSizeXs: '0.75rem',
  fontSizeSm: '0.875rem',
  fontSizeMd: '1rem',
  fontSizeLg: '1.125rem',
  fontSizeXl: '1.375rem',
  fontWeightRegular: 400,
  fontWeightMedium: 500,
  fontWeightSemibold: 600,
  letterSpacingWide: '0.14em',
} as const;

const baseThemeTokens = {
  spacing: {
    xs: '0.25rem',
    sm: '0.5rem',
    md: '0.75rem',
    lg: '1rem',
    xl: '1.5rem',
    xxl: '2rem',
  },
  radius: {
    sm: '0.25rem',
    md: '0.5rem',
    lg: '0.75rem',
    xl: '1rem',
    pill: '9999px',
  },
  border: {
    widthThin: '1px',
    widthBase: '1px',
    widthThick: '2px',
  },
  shadow: {
    panel: '0 1px 2px rgba(16, 35, 61, 0.08)',
    popover: '0 8px 24px rgba(16, 35, 61, 0.14)',
    focus: '0 0 0 3px rgba(49, 104, 255, 0.28)',
  },
  motion: {
    durationFastMs: 120,
    durationNormalMs: 180,
    durationSlowMs: 280,
    easingStandard: 'cubic-bezier(0.2, 0, 0, 1)',
  },
  typography: baseTypography,
} as const;

const themes: ThemeDefinition[] = [
  {
    id: ThemeId.Light,
    name: 'Light',
    description: 'Clean neutral daylight palette with balanced contrast.',
    version: '1.0.0',
    isHighContrast: false,
    defaultForApp: true,
    tokens: {
      ...baseThemeTokens,
      color: {
        neutral50: '#F8FAFD',
        neutral100: '#EEF2F8',
        neutral200: '#D9DFEA',
        neutral300: '#B8C2D6',
        neutral400: '#94A3B8',
        neutral500: '#64748B',
        neutral600: '#475569',
        neutral700: '#334155',
        neutral800: '#1F2937',
        neutral900: '#10233D',
        appBackground: '#F2F5FB',
        surfacePrimary: '#FFFFFF',
        surfaceSecondary: '#F8FAFD',
        surfaceMuted: '#EEF2F8',
        overlay: '#FFFFFFD9',
        borderSubtle: '#E5EAF3',
        borderPrimary: '#D9DFEA',
        borderStrong: '#B8C2D6',
        textPrimary: '#10233D',
        textSecondary: '#334155',
        textMuted: '#64748B',
        textInverse: '#FFFFFF',
        focusRing: '#3168FF',
        interactivePrimary: '#1A365D',
        interactivePrimaryHover: '#112844',
        interactiveSecondary: '#E7EEF9',
        interactiveSecondaryHover: '#D9E6FF',
        positive: '#15803D',
        negative: '#B91C1C',
        warning: '#A16207',
        info: '#1D4ED8',
        chartGrid: '#E8EDF6',
        chartAxis: '#B8C2D6',
        chartText: '#64748B',
        chartTooltipBackground: '#FFFFFF',
        chartTooltipBorder: '#D9DFEA',
        chartTooltipText: '#10233D',
        brandNavy: '#1A365D',
        brandBlue: '#3168FF',
        assetStocks: '#4A90D9',
        assetBonds: '#2EAD8E',
        assetCash: '#D9A441',
        mcBandOuter: '#93C5FD55',
        mcBandInner: '#60A5FA66',
        stressBase: '#334155',
        stressScenarioA: '#E67E22',
        stressScenarioB: '#8E44AD',
        stressScenarioC: '#16A085',
        stressScenarioD: '#2C3E80',
      },
      state: {
        editedCellBackground: '#DBEAFE',
        preservedRowBackground: '#E2E8F0',
        staleBackground: '#FEF3C7',
        staleText: '#92400E',
        selectedCellOutline: '#2563EB',
      },
      chart: {
        manualLine: '#1A365D',
        manualAreaTop: '#1A365D33',
        manualAreaBottom: '#1A365D08',
        mcMedianLine: '#1A365D',
        mcBandOuter: '#93C5FD55',
        mcBandInner: '#60A5FA66',
      },
    },
  },
  {
    id: ThemeId.Dark,
    name: 'Dark',
    description: 'Low-glare dark interface with cool highlights.',
    version: '1.0.0',
    isHighContrast: false,
    defaultForApp: false,
    tokens: {
      ...baseThemeTokens,
      color: {
        neutral50: '#17233D',
        neutral100: '#1E2A43',
        neutral200: '#25324B',
        neutral300: '#30415F',
        neutral400: '#3D547A',
        neutral500: '#64748B',
        neutral600: '#94A3B8',
        neutral700: '#A9B6CB',
        neutral800: '#CBD5E1',
        neutral900: '#E2E8F0',
        appBackground: '#0B1220',
        surfacePrimary: '#111A2D',
        surfaceSecondary: '#17233D',
        surfaceMuted: '#1E2A43',
        overlay: '#101A2DE6',
        borderSubtle: '#25324B',
        borderPrimary: '#30415F',
        borderStrong: '#3D547A',
        textPrimary: '#E2E8F0',
        textSecondary: '#CBD5E1',
        textMuted: '#94A3B8',
        textInverse: '#FFFFFF',
        focusRing: '#60A5FA',
        interactivePrimary: '#2563EB',
        interactivePrimaryHover: '#1D4ED8',
        interactiveSecondary: '#23334F',
        interactiveSecondaryHover: '#2F4263',
        positive: '#4ADE80',
        negative: '#F87171',
        warning: '#FBBF24',
        info: '#60A5FA',
        chartGrid: '#25324B',
        chartAxis: '#3D547A',
        chartText: '#A9B6CB',
        chartTooltipBackground: '#111A2D',
        chartTooltipBorder: '#30415F',
        chartTooltipText: '#E2E8F0',
        brandNavy: '#A5B4FC',
        brandBlue: '#60A5FA',
        assetStocks: '#60A5FA',
        assetBonds: '#34D399',
        assetCash: '#FBBF24',
        mcBandOuter: '#1D4ED866',
        mcBandInner: '#3B82F699',
        stressBase: '#CBD5E1',
        stressScenarioA: '#FB923C',
        stressScenarioB: '#C084FC',
        stressScenarioC: '#2DD4BF',
        stressScenarioD: '#93C5FD',
      },
      state: {
        editedCellBackground: '#1D4ED833',
        preservedRowBackground: '#1E293B',
        staleBackground: '#78350F',
        staleText: '#FDE68A',
        selectedCellOutline: '#60A5FA',
      },
      chart: {
        manualLine: '#C7D2FE',
        manualAreaTop: '#93C5FD4D',
        manualAreaBottom: '#93C5FD14',
        mcMedianLine: '#C7D2FE',
        mcBandOuter: '#1D4ED866',
        mcBandInner: '#3B82F699',
      },
    },
  },
  {
    id: ThemeId.Monokai,
    name: 'Monokai',
    description: 'VS Code Monokai-inspired dark palette with vivid chart and table accents.',
    version: '1.0.0',
    isHighContrast: false,
    defaultForApp: false,
    tokens: {
      ...baseThemeTokens,
      typography: {
        ...baseTypography,
        letterSpacingWide: '0.12em',
      },
      shadow: {
        panel: '0 1px 2px rgba(0, 0, 0, 0.45)',
        popover: '0 10px 28px rgba(0, 0, 0, 0.52)',
        focus: '0 0 0 3px rgba(102, 217, 239, 0.35)',
      },
      color: {
        neutral50: '#1E1F1C',
        neutral100: '#23241F',
        neutral200: '#2D2E28',
        neutral300: '#3A3B34',
        neutral400: '#5C5D57',
        neutral500: '#75715E',
        neutral600: '#A59F85',
        neutral700: '#C8C1A3',
        neutral800: '#E2DDD0',
        neutral900: '#F8F8F2',
        appBackground: '#1E1F1C',
        surfacePrimary: '#23241F',
        surfaceSecondary: '#2A2B24',
        surfaceMuted: '#32332C',
        overlay: '#23241FE6',
        borderSubtle: '#3A3B34',
        borderPrimary: '#4A4B43',
        borderStrong: '#5C5D57',
        textPrimary: '#F8F8F2',
        textSecondary: '#DAD6C8',
        textMuted: '#A59F85',
        textInverse: '#1E1F1C',
        focusRing: '#66D9EF',
        interactivePrimary: '#66D9EF',
        interactivePrimaryHover: '#5AC4D8',
        interactiveSecondary: '#3A3B34',
        interactiveSecondaryHover: '#4A4B43',
        positive: '#A6E22E',
        negative: '#F92672',
        warning: '#FD971F',
        info: '#66D9EF',
        chartGrid: '#3A3B34',
        chartAxis: '#5C5D57',
        chartText: '#C8C1A3',
        chartTooltipBackground: '#2A2B24',
        chartTooltipBorder: '#5C5D57',
        chartTooltipText: '#F8F8F2',
        brandNavy: '#C8C1A3',
        brandBlue: '#66D9EF',
        assetStocks: '#A6E22E',
        assetBonds: '#66D9EF',
        assetCash: '#FD971F',
        mcBandOuter: '#66D9EF44',
        mcBandInner: '#66D9EF77',
        stressBase: '#F8F8F2',
        stressScenarioA: '#FD971F',
        stressScenarioB: '#AE81FF',
        stressScenarioC: '#A6E22E',
        stressScenarioD: '#F92672',
      },
      state: {
        editedCellBackground: '#66D9EF26',
        preservedRowBackground: '#2D2E28',
        staleBackground: '#4C2F11',
        staleText: '#FDCC8A',
        selectedCellOutline: '#66D9EF',
      },
      chart: {
        manualLine: '#F8F8F2',
        manualAreaTop: '#66D9EF4D',
        manualAreaBottom: '#66D9EF14',
        mcMedianLine: '#F8F8F2',
        mcBandOuter: '#66D9EF44',
        mcBandInner: '#66D9EF77',
      },
    },
  },
  {
    id: ThemeId.HighContrast,
    name: 'High Contrast',
    description: 'Accessibility-first palette optimized for strong separation and legibility.',
    version: '1.0.0',
    isHighContrast: true,
    defaultForApp: false,
    tokens: {
      ...baseThemeTokens,
      typography: {
        ...baseTypography,
        fontSans: 'atkinsonHyperlegible',
      },
      color: {
        neutral50: '#111111',
        neutral100: '#171717',
        neutral200: '#1F2937',
        neutral300: '#374151',
        neutral400: '#6B7280',
        neutral500: '#9CA3AF',
        neutral600: '#D1D5DB',
        neutral700: '#E5E7EB',
        neutral800: '#F3F4F6',
        neutral900: '#FFFFFF',
        appBackground: '#000000',
        surfacePrimary: '#000000',
        surfaceSecondary: '#111111',
        surfaceMuted: '#171717',
        overlay: '#000000F2',
        borderSubtle: '#FFFFFF',
        borderPrimary: '#FFFFFF',
        borderStrong: '#FFFFFF',
        textPrimary: '#FFFFFF',
        textSecondary: '#FFFFFF',
        textMuted: '#E5E7EB',
        textInverse: '#000000',
        focusRing: '#FDE047',
        interactivePrimary: '#FFFFFF',
        interactivePrimaryHover: '#E5E7EB',
        interactiveSecondary: '#000000',
        interactiveSecondaryHover: '#111111',
        positive: '#4ADE80',
        negative: '#FCA5A5',
        warning: '#FDE047',
        info: '#93C5FD',
        chartGrid: '#FFFFFF',
        chartAxis: '#FFFFFF',
        chartText: '#FFFFFF',
        chartTooltipBackground: '#000000',
        chartTooltipBorder: '#FFFFFF',
        chartTooltipText: '#FFFFFF',
        brandNavy: '#FFFFFF',
        brandBlue: '#FDE047',
        assetStocks: '#93C5FD',
        assetBonds: '#6EE7B7',
        assetCash: '#FDE047',
        mcBandOuter: '#BFDBFE88',
        mcBandInner: '#60A5FA99',
        stressBase: '#FFFFFF',
        stressScenarioA: '#F59E0B',
        stressScenarioB: '#C084FC',
        stressScenarioC: '#2DD4BF',
        stressScenarioD: '#60A5FA',
      },
      state: {
        editedCellBackground: '#1E3A8A',
        preservedRowBackground: '#1F2937',
        staleBackground: '#78350F',
        staleText: '#FDE047',
        selectedCellOutline: '#FDE047',
      },
      chart: {
        manualLine: '#FFFFFF',
        manualAreaTop: '#FFFFFF55',
        manualAreaBottom: '#FFFFFF11',
        mcMedianLine: '#FFFFFF',
        mcBandOuter: '#BFDBFE88',
        mcBandInner: '#60A5FA99',
      },
    },
  },
];

const catalog: ThemeCatalogItem[] = themes.map((theme) => ({
  id: theme.id,
  name: theme.name,
  description: theme.description,
  version: theme.version,
  isHighContrast: theme.isHighContrast,
  defaultForApp: theme.defaultForApp,
}));

const defaultTheme = themes.find((theme) => theme.defaultForApp);
if (!defaultTheme) {
  throw new Error('Theme registry must include one default theme.');
}

const validationIssues: ThemeValidationIssue[] = themes.flatMap((theme) => validateThemeAccessibility(theme));

const responsePayload: ThemesResponse = {
  defaultThemeId: defaultTheme.id,
  themes,
  catalog,
  validationIssues,
};

themesResponseSchema.parse(responsePayload);

export const getThemesResponse = (): ThemesResponse => responsePayload;
