import {
  ThemeId,
  themesResponseSchema,
  type ThemeCatalogItem,
  type ThemeDefinition,
  type ThemeSlotCatalogItem,
  type ThemeTokenMap,
  type ThemeTokenRefOrValue,
  type ThemesResponse,
  type ThemeValidationIssue,
} from '@finapp/shared';

import { validateThemeAccessibility, validateThemeTokenModel } from './validation';

const baseTypography = {
  fontSans: 'ibmPlexSans',
  fontMono: 'ibmPlexMono',
  fontSizeXs: '0.75rem',
  fontSizeSm: '0.875rem',
  fontSizeMd: '1rem',
  fontSizeLg: '1.125rem',
  fontSizeXl: '1.375rem',
  fontWeightRegular: 400,
  fontWeightMedium: 500,
  fontWeightSemibold: 600,
  letterSpacingWide: '0.14em',
} as const;

const baseThemeTokens = {
  spacing: {
    xs: '0.25rem',
    sm: '0.5rem',
    md: '0.75rem',
    lg: '1rem',
    xl: '1.5rem',
    xxl: '2rem',
  },
  radius: {
    sm: '0.25rem',
    md: '0.5rem',
    lg: '0.75rem',
    xl: '1rem',
    pill: '9999px',
  },
  border: {
    widthThin: '1px',
    widthBase: '1px',
    widthThick: '2px',
  },
  shadow: {
    panel: '0 1px 2px rgba(16, 35, 61, 0.08)',
    popover: '0 8px 24px rgba(16, 35, 61, 0.14)',
    focus: '0 0 0 3px rgba(49, 104, 255, 0.28)',
  },
  motion: {
    durationFastMs: 120,
    durationNormalMs: 180,
    durationSlowMs: 280,
    easingStandard: 'cubic-bezier(0.2, 0, 0, 1)',
  },
  typography: baseTypography,
} as const;

type BaseThemeDefinition = Omit<ThemeDefinition, 'tokenModelVersion' | 'semantic' | 'slots' | 'overrides'>;

const defaultSlotMap: ThemeTokenMap = {
  'appShell.root.bg': { ref: 'semantic.surface.app' },
  'appShell.root.text': { ref: 'semantic.text.primary' },
  'appShell.sidebar.bg': { ref: 'semantic.surface.panel' },
  'appShell.sidebar.border': { ref: 'semantic.border.default' },
  'appShell.main.bg': { ref: 'semantic.surface.app' },
  'debugStatusPanel.bg': { ref: 'semantic.surface.card' },
  'debugStatusPanel.border': { ref: 'semantic.border.default' },
  'debugStatusPanel.text': { ref: 'semantic.text.secondary' },
  'debugStatusPanel.error': { ref: 'semantic.status.negative' },
  'commandBar.shell.bg': { ref: 'semantic.surface.overlay' },
  'commandBar.shell.border': { ref: 'semantic.border.default' },
  'commandBar.logo.badge.bg': { ref: 'semantic.brand.secondary' },
  'commandBar.logo.badge.text': { ref: 'semantic.text.inverse' },
  'commandBar.logo.text': { ref: 'semantic.text.primary' },
  'commandBar.sectionLabel.text': { ref: 'semantic.text.muted' },
  'commandBar.message.text': { ref: 'semantic.text.secondary' },
  'commandBar.actionButton.bg': { ref: 'semantic.surface.card' },
  'commandBar.actionButton.border': { ref: 'semantic.border.default' },
  'commandBar.actionButton.text': { ref: 'semantic.text.secondary' },
  'commandBar.actionButton.hoverText': { ref: 'semantic.brand.secondary' },
  'commandBar.actionButton.hoverBorder': { ref: 'semantic.brand.secondary' },
  'commandBar.primaryAction.bg': { ref: 'semantic.interactive.primary.bg' },
  'commandBar.primaryAction.text': { ref: 'semantic.interactive.primary.text' },
  'commandBar.primaryAction.disabledBg': { ref: 'semantic.surface.disabled' },
  'commandBar.popover.bg': { ref: 'semantic.surface.card' },
  'commandBar.popover.border': { ref: 'semantic.border.default' },
  'commandBar.popover.title': { ref: 'semantic.text.muted' },
  'commandBar.popover.item': { ref: 'semantic.text.secondary' },
  'commandBar.popover.itemHoverBg': { ref: 'semantic.surface.muted' },
  'commandBar.popover.itemActiveBg': { ref: 'semantic.surface.panel' },
  'commandBar.tooltip.bg': { ref: 'semantic.surface.tooltip' },
  'commandBar.tooltip.text': { ref: 'semantic.text.inverse' },
  'commandBar.modal.backdrop': 'color-mix(in srgb, var(--theme-color-text-primary) 45%, transparent)',
  'commandBar.modal.bg': { ref: 'semantic.surface.card' },
  'commandBar.modal.border': { ref: 'semantic.border.default' },
  'commandBar.modal.title': { ref: 'semantic.text.primary' },
  'commandBar.modal.text': { ref: 'semantic.text.secondary' },
  'sidebar.compareCard.bg': { ref: 'semantic.surface.panel' },
  'sidebar.compareCard.border': { ref: 'semantic.border.default' },
  'sidebar.compareCard.title': { ref: 'semantic.text.muted' },
  'sidebar.compareCard.text': { ref: 'semantic.text.secondary' },
  'section.card.bg': { ref: 'semantic.surface.card' },
  'section.card.border': { ref: 'semantic.border.default' },
  'section.header.title': { ref: 'semantic.brand.primary' },
  'section.header.icon': { ref: 'semantic.text.secondary' },
  'section.divider': { ref: 'semantic.border.default' },
  'syncControl.master.locked.bg': { ref: 'semantic.brand.primary' },
  'syncControl.master.locked.text': { ref: 'semantic.text.inverse' },
  'syncControl.master.unlocked.bg': { ref: 'semantic.surface.card' },
  'syncControl.master.unlocked.text': { ref: 'semantic.text.secondary' },
  'syncControl.follower.synced.bg': 'color-mix(in srgb, var(--theme-color-positive) 14%, var(--theme-color-surface-primary))',
  'syncControl.follower.synced.text': { ref: 'semantic.status.positive' },
  'syncControl.follower.unsynced.bg': 'color-mix(in srgb, var(--theme-color-warning) 18%, var(--theme-color-surface-primary))',
  'syncControl.follower.unsynced.text': { ref: 'semantic.status.warning' },
  'inputs.control.bg': { ref: 'semantic.surface.card' },
  'inputs.control.border': { ref: 'semantic.border.default' },
  'inputs.control.text': { ref: 'semantic.text.primary' },
  'inputs.control.placeholder': { ref: 'semantic.text.muted' },
  'inputs.control.disabledBg': { ref: 'semantic.surface.disabled' },
  'inputs.label.text': { ref: 'semantic.text.secondary' },
  'inputs.helper.text': { ref: 'semantic.text.muted' },
  'inputs.addButton.border': { ref: 'semantic.brand.primary' },
  'inputs.addButton.text': { ref: 'semantic.brand.primary' },
  'inputs.removeButton.text': { ref: 'semantic.text.secondary' },
  'startingPortfolio.donut.innerBg': { ref: 'semantic.surface.card' },
  'summaryStats.shell.bg': { ref: 'semantic.surface.panel' },
  'summaryStats.card.bg': { ref: 'semantic.surface.card' },
  'summaryStats.card.border': { ref: 'semantic.border.default' },
  'summaryStats.label.text': { ref: 'semantic.text.muted' },
  'summaryStats.value.text': { ref: 'semantic.text.primary' },
  'summaryStats.value.positive': { ref: 'semantic.status.positive' },
  'summaryStats.value.negative': { ref: 'semantic.status.negative' },
  'summaryStats.annotation.text': { ref: 'semantic.text.muted' },
  'chartPanel.shell.bg': { ref: 'semantic.surface.card' },
  'chartPanel.shell.border': { ref: 'semantic.border.default' },
  'chartPanel.heading.text': { ref: 'semantic.text.muted' },
  'chartPanel.overlay.bg': 'color-mix(in srgb, var(--theme-color-surface-primary) 65%, transparent)',
  'chartPanel.overlay.text': { ref: 'semantic.text.secondary' },
  'chartPanel.overlay.spinner': { ref: 'semantic.brand.secondary' },
  'portfolioChart.axis': { ref: 'semantic.chart.axis' },
  'portfolioChart.grid': { ref: 'semantic.chart.grid' },
  'portfolioChart.text': { ref: 'semantic.chart.text' },
  'portfolioChart.tooltip.bg': { ref: 'semantic.chart.tooltip.bg' },
  'portfolioChart.tooltip.border': { ref: 'semantic.chart.tooltip.border' },
  'portfolioChart.tooltip.text': { ref: 'semantic.chart.tooltip.text' },
  'withdrawalChart.axis': { ref: 'semantic.chart.axis' },
  'withdrawalChart.grid': { ref: 'semantic.chart.grid' },
  'withdrawalChart.text': { ref: 'semantic.chart.text' },
  'withdrawalChart.tooltip.bg': { ref: 'semantic.chart.tooltip.bg' },
  'withdrawalChart.tooltip.border': { ref: 'semantic.chart.tooltip.border' },
  'withdrawalChart.tooltip.text': { ref: 'semantic.chart.tooltip.text' },
  'compareDiffTable.shell.bg': { ref: 'semantic.surface.card' },
  'compareDiffTable.shell.border': { ref: 'semantic.border.default' },
  'compareDiffTable.header.bg': { ref: 'semantic.surface.panel' },
  'compareDiffTable.header.text': { ref: 'semantic.text.secondary' },
  'compareDiffTable.group.bg': { ref: 'semantic.surface.muted' },
  'compareDiffTable.group.text': { ref: 'semantic.text.secondary' },
  'compareDiffTable.diffCell.bg': 'color-mix(in srgb, var(--theme-color-info) 10%, var(--theme-color-surface-primary))',
  'detailLedger.shell.bg': { ref: 'semantic.surface.card' },
  'detailLedger.shell.border': { ref: 'semantic.border.default' },
  'detailLedger.header.bg': { ref: 'semantic.surface.card' },
  'detailLedger.header.text': { ref: 'semantic.text.secondary' },
  'detailLedger.toolbar.title': { ref: 'semantic.text.primary' },
  'detailLedger.toolbar.subtitle': { ref: 'semantic.text.muted' },
  'detailLedger.reference.bg': { ref: 'semantic.surface.muted' },
  'detailLedger.reference.text': { ref: 'semantic.text.secondary' },
  'detailLedger.cell.focusBg': { ref: 'semantic.interactive.secondary.bg' },
  'detailLedger.cell.focusOutline': { ref: 'semantic.state.selected' },
  'detailLedger.cell.editedBg': { ref: 'semantic.state.edited' },
  'detailLedger.row.preservedBg': { ref: 'semantic.state.preserved' },
  'detailLedger.stale.bg': { ref: 'semantic.state.stale.bg' },
  'detailLedger.stale.text': { ref: 'semantic.state.stale.text' },
  'stressPanel.shell.bg': { ref: 'semantic.surface.card' },
  'stressPanel.shell.border': { ref: 'semantic.border.default' },
  'stressPanel.header.bg': { ref: 'semantic.surface.panel' },
  'stressPanel.header.text': { ref: 'semantic.text.primary' },
  'stressPanel.card.bg': { ref: 'semantic.surface.card' },
  'stressPanel.card.border': { ref: 'semantic.border.default' },
  'stressPanel.metricTable.headerBg': { ref: 'semantic.surface.muted' },
  'stressPanel.metricTable.headerText': { ref: 'semantic.text.secondary' },
  'stressPanel.metricTable.rowText': { ref: 'semantic.text.secondary' },
  'stressPanel.metricTable.deltaText': { ref: 'semantic.status.negative' },
};

const slotCatalog: ThemeSlotCatalogItem[] = Object.entries(defaultSlotMap).map(([path, fallback]) => ({
  path,
  category: path.split('.')[0] ?? 'app',
  description: `${path} themed slot`,
  fallback,
}));

const buildSemanticMap = (theme: BaseThemeDefinition): ThemeTokenMap => ({
  'semantic.surface.app': theme.tokens.color.appBackground,
  'semantic.surface.card': theme.tokens.color.surfacePrimary,
  'semantic.surface.panel': theme.tokens.color.surfaceMuted,
  'semantic.surface.muted': theme.tokens.color.surfaceSecondary,
  'semantic.surface.overlay': theme.tokens.color.overlay,
  'semantic.surface.disabled': theme.tokens.color.surfaceSecondary,
  'semantic.surface.tooltip': theme.tokens.color.chartTooltipBackground,
  'semantic.border.default': theme.tokens.color.borderPrimary,
  'semantic.border.subtle': theme.tokens.color.borderSubtle,
  'semantic.border.strong': theme.tokens.color.borderStrong,
  'semantic.text.primary': theme.tokens.color.textPrimary,
  'semantic.text.secondary': theme.tokens.color.textSecondary,
  'semantic.text.muted': theme.tokens.color.textMuted,
  'semantic.text.inverse': theme.tokens.color.textInverse,
  'semantic.brand.primary': theme.tokens.color.brandNavy,
  'semantic.brand.secondary': theme.tokens.color.brandBlue,
  'semantic.interactive.primary.bg': theme.tokens.color.interactivePrimary,
  'semantic.interactive.primary.text': theme.tokens.color.textInverse,
  'semantic.interactive.primary.hover': theme.tokens.color.interactivePrimaryHover,
  'semantic.interactive.secondary.bg': theme.tokens.color.interactiveSecondary,
  'semantic.interactive.secondary.hover': theme.tokens.color.interactiveSecondaryHover,
  'semantic.status.positive': theme.tokens.color.positive,
  'semantic.status.negative': theme.tokens.color.negative,
  'semantic.status.warning': theme.tokens.color.warning,
  'semantic.status.info': theme.tokens.color.info,
  'semantic.chart.axis': theme.tokens.color.chartAxis,
  'semantic.chart.grid': theme.tokens.color.chartGrid,
  'semantic.chart.text': theme.tokens.color.chartText,
  'semantic.chart.tooltip.bg': theme.tokens.color.chartTooltipBackground,
  'semantic.chart.tooltip.border': theme.tokens.color.chartTooltipBorder,
  'semantic.chart.tooltip.text': theme.tokens.color.chartTooltipText,
  'semantic.state.edited': theme.tokens.state.editedCellBackground,
  'semantic.state.preserved': theme.tokens.state.preservedRowBackground,
  'semantic.state.stale.bg': theme.tokens.state.staleBackground,
  'semantic.state.stale.text': theme.tokens.state.staleText,
  'semantic.state.selected': theme.tokens.state.selectedCellOutline,
});

const resolveTokenRefString = (token: ThemeTokenRefOrValue): string =>
  typeof token === 'string' ? token : token.ref;

const baseThemes: BaseThemeDefinition[] = [
  {
    id: ThemeId.Light,
    name: 'Light',
    description: 'Clean neutral daylight palette with balanced contrast.',
    version: '1.0.0',
    isHighContrast: false,
    defaultForApp: true,
    tokens: {
      ...baseThemeTokens,
      color: {
        neutral50: '#F8FAFD',
        neutral100: '#EEF2F8',
        neutral200: '#D9DFEA',
        neutral300: '#B8C2D6',
        neutral400: '#94A3B8',
        neutral500: '#64748B',
        neutral600: '#475569',
        neutral700: '#334155',
        neutral800: '#1F2937',
        neutral900: '#10233D',
        appBackground: '#F2F5FB',
        surfacePrimary: '#FFFFFF',
        surfaceSecondary: '#F8FAFD',
        surfaceMuted: '#EEF2F8',
        overlay: '#FFFFFFD9',
        borderSubtle: '#E5EAF3',
        borderPrimary: '#D9DFEA',
        borderStrong: '#B8C2D6',
        textPrimary: '#10233D',
        textSecondary: '#334155',
        textMuted: '#64748B',
        textInverse: '#FFFFFF',
        focusRing: '#3168FF',
        interactivePrimary: '#1A365D',
        interactivePrimaryHover: '#112844',
        interactiveSecondary: '#E7EEF9',
        interactiveSecondaryHover: '#D9E6FF',
        positive: '#15803D',
        negative: '#B91C1C',
        warning: '#A16207',
        info: '#1D4ED8',
        chartGrid: '#E8EDF6',
        chartAxis: '#B8C2D6',
        chartText: '#64748B',
        chartTooltipBackground: '#FFFFFF',
        chartTooltipBorder: '#D9DFEA',
        chartTooltipText: '#10233D',
        brandNavy: '#1A365D',
        brandBlue: '#3168FF',
        assetStocks: '#4A90D9',
        assetBonds: '#2EAD8E',
        assetCash: '#D9A441',
        mcBandOuter: '#93C5FD55',
        mcBandInner: '#60A5FA66',
        stressBase: '#334155',
        stressScenarioA: '#E67E22',
        stressScenarioB: '#8E44AD',
        stressScenarioC: '#16A085',
        stressScenarioD: '#2C3E80',
      },
      state: {
        editedCellBackground: '#DBEAFE',
        preservedRowBackground: '#E2E8F0',
        staleBackground: '#FEF3C7',
        staleText: '#92400E',
        selectedCellOutline: '#2563EB',
      },
      chart: {
        manualLine: '#1A365D',
        manualAreaTop: '#1A365D33',
        manualAreaBottom: '#1A365D08',
        mcMedianLine: '#1A365D',
        mcBandOuter: '#93C5FD55',
        mcBandInner: '#60A5FA66',
        compareSlotA: '#1A365D',
        compareSlotB: '#3168FF',
        compareSlotC: '#15803D',
        compareSlotD: '#A16207',
        compareSlotE: '#7C3AED',
        compareSlotF: '#0F766E',
        compareSlotG: '#C2410C',
        compareSlotH: '#475569',
      },
    },
  },
  {
    id: ThemeId.Dark,
    name: 'Dark',
    description: 'Low-glare dark interface with cool highlights.',
    version: '1.0.0',
    isHighContrast: false,
    defaultForApp: false,
    tokens: {
      ...baseThemeTokens,
      color: {
        neutral50: '#17233D',
        neutral100: '#1E2A43',
        neutral200: '#25324B',
        neutral300: '#30415F',
        neutral400: '#3D547A',
        neutral500: '#64748B',
        neutral600: '#94A3B8',
        neutral700: '#A9B6CB',
        neutral800: '#CBD5E1',
        neutral900: '#E2E8F0',
        appBackground: '#0B1220',
        surfacePrimary: '#111A2D',
        surfaceSecondary: '#17233D',
        surfaceMuted: '#1E2A43',
        overlay: '#101A2DE6',
        borderSubtle: '#25324B',
        borderPrimary: '#30415F',
        borderStrong: '#3D547A',
        textPrimary: '#E2E8F0',
        textSecondary: '#CBD5E1',
        textMuted: '#94A3B8',
        textInverse: '#FFFFFF',
        focusRing: '#60A5FA',
        interactivePrimary: '#2563EB',
        interactivePrimaryHover: '#1D4ED8',
        interactiveSecondary: '#23334F',
        interactiveSecondaryHover: '#2F4263',
        positive: '#4ADE80',
        negative: '#F87171',
        warning: '#FBBF24',
        info: '#60A5FA',
        chartGrid: '#25324B',
        chartAxis: '#3D547A',
        chartText: '#A9B6CB',
        chartTooltipBackground: '#111A2D',
        chartTooltipBorder: '#30415F',
        chartTooltipText: '#E2E8F0',
        brandNavy: '#A5B4FC',
        brandBlue: '#60A5FA',
        assetStocks: '#60A5FA',
        assetBonds: '#34D399',
        assetCash: '#FBBF24',
        mcBandOuter: '#1D4ED866',
        mcBandInner: '#3B82F699',
        stressBase: '#CBD5E1',
        stressScenarioA: '#FB923C',
        stressScenarioB: '#C084FC',
        stressScenarioC: '#2DD4BF',
        stressScenarioD: '#93C5FD',
      },
      state: {
        editedCellBackground: '#1D4ED833',
        preservedRowBackground: '#1E293B',
        staleBackground: '#78350F',
        staleText: '#FDE68A',
        selectedCellOutline: '#60A5FA',
      },
      chart: {
        manualLine: '#C7D2FE',
        manualAreaTop: '#93C5FD4D',
        manualAreaBottom: '#93C5FD14',
        mcMedianLine: '#C7D2FE',
        mcBandOuter: '#1D4ED866',
        mcBandInner: '#3B82F699',
        compareSlotA: '#C7D2FE',
        compareSlotB: '#60A5FA',
        compareSlotC: '#4ADE80',
        compareSlotD: '#FBBF24',
        compareSlotE: '#C084FC',
        compareSlotF: '#2DD4BF',
        compareSlotG: '#FB923C',
        compareSlotH: '#A9B6CB',
      },
    },
  },
  {
    id: ThemeId.Monokai,
    name: 'Monokai',
    description: 'VS Code Monokai-inspired dark palette with vivid chart and table accents.',
    version: '1.0.0',
    isHighContrast: false,
    defaultForApp: false,
    tokens: {
      ...baseThemeTokens,
      typography: {
        ...baseTypography,
        letterSpacingWide: '0.12em',
      },
      shadow: {
        panel: '0 1px 2px rgba(0, 0, 0, 0.45)',
        popover: '0 10px 28px rgba(0, 0, 0, 0.52)',
        focus: '0 0 0 3px rgba(102, 217, 239, 0.35)',
      },
      color: {
        neutral50: '#1E1F1C',
        neutral100: '#23241F',
        neutral200: '#2D2E28',
        neutral300: '#3A3B34',
        neutral400: '#5C5D57',
        neutral500: '#75715E',
        neutral600: '#A59F85',
        neutral700: '#C8C1A3',
        neutral800: '#E2DDD0',
        neutral900: '#F8F8F2',
        appBackground: '#1E1F1C',
        surfacePrimary: '#23241F',
        surfaceSecondary: '#2A2B24',
        surfaceMuted: '#32332C',
        overlay: '#23241FE6',
        borderSubtle: '#3A3B34',
        borderPrimary: '#4A4B43',
        borderStrong: '#5C5D57',
        textPrimary: '#F8F8F2',
        textSecondary: '#DAD6C8',
        textMuted: '#A59F85',
        textInverse: '#1E1F1C',
        focusRing: '#66D9EF',
        interactivePrimary: '#66D9EF',
        interactivePrimaryHover: '#5AC4D8',
        interactiveSecondary: '#3A3B34',
        interactiveSecondaryHover: '#4A4B43',
        positive: '#A6E22E',
        negative: '#F92672',
        warning: '#FD971F',
        info: '#66D9EF',
        chartGrid: '#3A3B34',
        chartAxis: '#5C5D57',
        chartText: '#C8C1A3',
        chartTooltipBackground: '#2A2B24',
        chartTooltipBorder: '#5C5D57',
        chartTooltipText: '#F8F8F2',
        brandNavy: '#C8C1A3',
        brandBlue: '#66D9EF',
        assetStocks: '#A6E22E',
        assetBonds: '#66D9EF',
        assetCash: '#FD971F',
        mcBandOuter: '#66D9EF44',
        mcBandInner: '#66D9EF77',
        stressBase: '#F8F8F2',
        stressScenarioA: '#FD971F',
        stressScenarioB: '#AE81FF',
        stressScenarioC: '#A6E22E',
        stressScenarioD: '#F92672',
      },
      state: {
        editedCellBackground: '#66D9EF26',
        preservedRowBackground: '#2D2E28',
        staleBackground: '#4C2F11',
        staleText: '#FDCC8A',
        selectedCellOutline: '#66D9EF',
      },
      chart: {
        manualLine: '#F8F8F2',
        manualAreaTop: '#66D9EF4D',
        manualAreaBottom: '#66D9EF14',
        mcMedianLine: '#F8F8F2',
        mcBandOuter: '#66D9EF44',
        mcBandInner: '#66D9EF77',
        compareSlotA: '#F8F8F2',
        compareSlotB: '#66D9EF',
        compareSlotC: '#A6E22E',
        compareSlotD: '#FD971F',
        compareSlotE: '#AE81FF',
        compareSlotF: '#2EC4B6',
        compareSlotG: '#F92672',
        compareSlotH: '#C8C1A3',
      },
    },
  },
  {
    id: ThemeId.Synthwave84,
    name: "Synthwave '84",
    description: "VS Code Synthwave '84-inspired neon dark palette by Robb Owen.",
    version: '1.0.0',
    isHighContrast: false,
    defaultForApp: false,
    tokens: {
      ...baseThemeTokens,
      typography: {
        ...baseTypography,
        letterSpacingWide: '0.16em',
      },
      shadow: {
        panel: '0 1px 2px rgba(13, 2, 33, 0.42)',
        popover: '0 12px 30px rgba(15, 0, 36, 0.56)',
        focus: '0 0 0 3px rgba(65, 232, 244, 0.38)',
      },
      color: {
        neutral50: '#0A0820',
        neutral100: '#100C2A',
        neutral200: '#161136',
        neutral300: '#24184A',
        neutral400: '#3A2A66',
        neutral500: '#6B5A91',
        neutral600: '#9B8BC0',
        neutral700: '#BFB2DF',
        neutral800: '#DDD2F2',
        neutral900: '#F4EEFF',
        appBackground: '#0B0A26',
        surfacePrimary: '#120D31',
        surfaceSecondary: '#17103C',
        surfaceMuted: '#1F1548',
        overlay: '#120D31E6',
        borderSubtle: '#2A1C57',
        borderPrimary: '#3A2A66',
        borderStrong: '#5A4688',
        textPrimary: '#F4EEFF',
        textSecondary: '#DDD2F2',
        textMuted: '#AF9BCD',
        textInverse: '#0B0A26',
        focusRing: '#41E8F4',
        interactivePrimary: '#F92AAD',
        interactivePrimaryHover: '#FF49BB',
        interactiveSecondary: '#24184A',
        interactiveSecondaryHover: '#34215D',
        positive: '#75F5A7',
        negative: '#FF5E9A',
        warning: '#FFC96A',
        info: '#41E8F4',
        chartGrid: '#261B55',
        chartAxis: '#4E3A80',
        chartText: '#CDBFE7',
        chartTooltipBackground: '#161136',
        chartTooltipBorder: '#5A4688',
        chartTooltipText: '#F4EEFF',
        brandNavy: '#D7CAEE',
        brandBlue: '#41E8F4',
        assetStocks: '#41E8F4',
        assetBonds: '#B57BFF',
        assetCash: '#FFC96A',
        mcBandOuter: '#41E8F440',
        mcBandInner: '#F92AAD55',
        stressBase: '#F4EEFF',
        stressScenarioA: '#F92AAD',
        stressScenarioB: '#41E8F4',
        stressScenarioC: '#B57BFF',
        stressScenarioD: '#FFC96A',
      },
      state: {
        editedCellBackground: '#41E8F42A',
        preservedRowBackground: '#1A1240',
        staleBackground: '#5A2E1C',
        staleText: '#FFD49D',
        selectedCellOutline: '#41E8F4',
      },
      chart: {
        manualLine: '#F4EEFF',
        manualAreaTop: '#F92AAD3A',
        manualAreaBottom: '#41E8F414',
        mcMedianLine: '#F4EEFF',
        mcBandOuter: '#41E8F440',
        mcBandInner: '#F92AAD55',
        compareSlotA: '#F4EEFF',
        compareSlotB: '#41E8F4',
        compareSlotC: '#75F5A7',
        compareSlotD: '#FFC96A',
        compareSlotE: '#B57BFF',
        compareSlotF: '#27D3D9',
        compareSlotG: '#F92AAD',
        compareSlotH: '#DDD2F2',
      },
    },
  },
  {
    id: ThemeId.StayTheCourse,
    name: 'Stay The Course',
    description: 'Dark theme with disciplined teal-forward accents and high legibility.',
    version: '1.0.0',
    isHighContrast: false,
    defaultForApp: false,
    tokens: {
      ...baseThemeTokens,
      shadow: {
        panel: '0 1px 2px rgba(0, 0, 0, 0.5)',
        popover: '0 10px 28px rgba(0, 0, 0, 0.58)',
        focus: '0 0 0 3px rgba(4, 242, 198, 0.36)',
      },
      color: {
        neutral50: '#0C0C0C',
        neutral100: '#111414',
        neutral200: '#171D1B',
        neutral300: '#1E2824',
        neutral400: '#2B3C35',
        neutral500: '#4C6B60',
        neutral600: '#78A897',
        neutral700: '#A2D6C2',
        neutral800: '#C5F0E1',
        neutral900: '#E6FFF7',
        appBackground: '#0C0C0C',
        surfacePrimary: '#111414',
        surfaceSecondary: '#171D1B',
        surfaceMuted: '#1E2824',
        overlay: '#111414E6',
        borderSubtle: '#1F332C',
        borderPrimary: '#2B4A3F',
        borderStrong: '#3E6B5A',
        textPrimary: '#E6FFF7',
        textSecondary: '#C5F0E1',
        textMuted: '#78A897',
        textInverse: '#0C0C0C',
        focusRing: '#04F2C6',
        interactivePrimary: '#04F2C6',
        interactivePrimaryHover: '#04F2AE',
        interactiveSecondary: '#1F332C',
        interactiveSecondaryHover: '#2B4A3F',
        positive: '#04F29B',
        negative: '#FF6B6B',
        warning: '#FFC857',
        info: '#04F2AE',
        chartGrid: '#1F332C',
        chartAxis: '#2B4A3F',
        chartText: '#A2D6C2',
        chartTooltipBackground: '#111414',
        chartTooltipBorder: '#3E6B5A',
        chartTooltipText: '#E6FFF7',
        brandNavy: '#A2D6C2',
        brandBlue: '#04F2C6',
        assetStocks: '#04F2C6',
        assetBonds: '#04F2AE',
        assetCash: '#048C65',
        mcBandOuter: '#04F2C644',
        mcBandInner: '#04F2AE66',
        stressBase: '#E6FFF7',
        stressScenarioA: '#04F2C6',
        stressScenarioB: '#04F2AE',
        stressScenarioC: '#04F29B',
        stressScenarioD: '#5BE8C7',
      },
      state: {
        editedCellBackground: '#04F2C626',
        preservedRowBackground: '#15201C',
        staleBackground: '#4F3A15',
        staleText: '#FFDFA3',
        selectedCellOutline: '#04F2C6',
      },
      chart: {
        manualLine: '#E6FFF7',
        manualAreaTop: '#04F2C63D',
        manualAreaBottom: '#04F2C612',
        mcMedianLine: '#E6FFF7',
        mcBandOuter: '#04F2C644',
        mcBandInner: '#04F2AE66',
        compareSlotA: '#E6FFF7',
        compareSlotB: '#04F2C6',
        compareSlotC: '#04F2AE',
        compareSlotD: '#04F29B',
        compareSlotE: '#048C65',
        compareSlotF: '#5BE8C7',
        compareSlotG: '#2FA387',
        compareSlotH: '#A2D6C2',
      },
    },
  },
  {
    id: ThemeId.HighContrast,
    name: 'High Contrast',
    description: 'Accessibility-first palette optimized for strong separation and legibility.',
    version: '1.0.0',
    isHighContrast: true,
    defaultForApp: false,
    tokens: {
      ...baseThemeTokens,
      typography: {
        ...baseTypography,
        fontSans: 'atkinsonHyperlegible',
      },
      color: {
        neutral50: '#111111',
        neutral100: '#171717',
        neutral200: '#1F2937',
        neutral300: '#374151',
        neutral400: '#6B7280',
        neutral500: '#9CA3AF',
        neutral600: '#D1D5DB',
        neutral700: '#E5E7EB',
        neutral800: '#F3F4F6',
        neutral900: '#FFFFFF',
        appBackground: '#000000',
        surfacePrimary: '#000000',
        surfaceSecondary: '#111111',
        surfaceMuted: '#171717',
        overlay: '#000000F2',
        borderSubtle: '#FFFFFF',
        borderPrimary: '#FFFFFF',
        borderStrong: '#FFFFFF',
        textPrimary: '#FFFFFF',
        textSecondary: '#FFFFFF',
        textMuted: '#E5E7EB',
        textInverse: '#000000',
        focusRing: '#FDE047',
        interactivePrimary: '#FFFFFF',
        interactivePrimaryHover: '#E5E7EB',
        interactiveSecondary: '#000000',
        interactiveSecondaryHover: '#111111',
        positive: '#4ADE80',
        negative: '#FCA5A5',
        warning: '#FDE047',
        info: '#93C5FD',
        chartGrid: '#FFFFFF',
        chartAxis: '#FFFFFF',
        chartText: '#FFFFFF',
        chartTooltipBackground: '#000000',
        chartTooltipBorder: '#FFFFFF',
        chartTooltipText: '#FFFFFF',
        brandNavy: '#FFFFFF',
        brandBlue: '#FDE047',
        assetStocks: '#93C5FD',
        assetBonds: '#6EE7B7',
        assetCash: '#FDE047',
        mcBandOuter: '#BFDBFE88',
        mcBandInner: '#60A5FA99',
        stressBase: '#FFFFFF',
        stressScenarioA: '#F59E0B',
        stressScenarioB: '#C084FC',
        stressScenarioC: '#2DD4BF',
        stressScenarioD: '#60A5FA',
      },
      state: {
        editedCellBackground: '#1E3A8A',
        preservedRowBackground: '#1F2937',
        staleBackground: '#78350F',
        staleText: '#FDE047',
        selectedCellOutline: '#FDE047',
      },
      chart: {
        manualLine: '#FFFFFF',
        manualAreaTop: '#FFFFFF55',
        manualAreaBottom: '#FFFFFF11',
        mcMedianLine: '#FFFFFF',
        mcBandOuter: '#BFDBFE88',
        mcBandInner: '#60A5FA99',
        compareSlotA: '#FFFFFF',
        compareSlotB: '#93C5FD',
        compareSlotC: '#4ADE80',
        compareSlotD: '#FDE047',
        compareSlotE: '#C084FC',
        compareSlotF: '#2DD4BF',
        compareSlotG: '#FCA5A5',
        compareSlotH: '#E5E7EB',
      },
    },
  },
];

const themes: ThemeDefinition[] = baseThemes.map((theme) => ({
  ...theme,
  tokenModelVersion: '2',
  semantic: buildSemanticMap(theme),
  slots: Object.fromEntries(
    Object.entries(defaultSlotMap).map(([path, fallback]) => [path, resolveTokenRefString(fallback)]),
  ),
  overrides: {},
}));

const catalog: ThemeCatalogItem[] = themes.map((theme) => ({
  id: theme.id,
  name: theme.name,
  description: theme.description,
  version: theme.version,
  isHighContrast: theme.isHighContrast,
  defaultForApp: theme.defaultForApp,
}));

const defaultTheme = themes.find((theme) => theme.defaultForApp);
if (!defaultTheme) {
  throw new Error('Theme registry must include one default theme.');
}

const validationIssues: ThemeValidationIssue[] = themes.flatMap((theme) => [
  ...validateThemeAccessibility(theme),
  ...validateThemeTokenModel(theme, slotCatalog),
]);

const responsePayload: ThemesResponse = {
  tokenModelVersion: '2',
  defaultThemeId: defaultTheme.id,
  themes,
  catalog,
  slotCatalog,
  validationIssues,
};

themesResponseSchema.parse(responsePayload);

export const getThemesResponse = (): ThemesResponse => responsePayload;
