export enum AssetClass {
  Stocks = 'stocks',
  Bonds = 'bonds',
  Cash = 'cash',
}

export enum WithdrawalStrategyType {
  ConstantDollar = 'constantDollar',
  PercentOfPortfolio = 'percentOfPortfolio',
  OneOverN = 'oneOverN',
  Vpw = 'vpw',
  DynamicSwr = 'dynamicSwr',
  DynamicSwrAdaptive = 'dynamicSwrAdaptive',
  SensibleWithdrawals = 'sensibleWithdrawals',
  NinetyFivePercent = 'ninetyFivePercent',
  GuytonKlinger = 'guytonKlinger',
  VanguardDynamic = 'vanguardDynamic',
  Endowment = 'endowment',
  HebelerAutopilot = 'hebelerAutopilot',
  CapeBased = 'capeBased',
}

export enum DrawdownStrategyType {
  Bucket = 'bucket',
  Rebalancing = 'rebalancing',
}

export enum SimulationMode {
  Manual = 'manual',
  MonteCarlo = 'monteCarlo',
}

export enum HistoricalEra {
  FullHistory = 'fullHistory',
  DepressionEra = 'depressionEra',
  PostWarBoom = 'postWarBoom',
  StagflationEra = 'stagflationEra',
  OilCrisis = 'oilCrisis',
  Post1980BullRun = 'post1980BullRun',
  LostDecade = 'lostDecade',
  PostGfcRecovery = 'postGfcRecovery',
}

export enum AppMode {
  Planning = 'planning',
  Tracking = 'tracking',
}

export enum ThemeId {
  Light = 'light',
  Dark = 'dark',
  HighContrast = 'highContrast',
  Monokai = 'monokai',
  Synthwave84 = 'synthwave84',
  StayTheCourse = 'stayTheCourse',
}

export enum ThemeFamilyId {
  Default = 'default',
  Monokai = 'monokai',
  Synthwave84 = 'synthwave84',
  StayTheCourse = 'stayTheCourse',
  HighContrast = 'highContrast',
  PatagoniaVest = 'patagoniaVest',
  MoneyNeverSleeps = 'moneyNeverSleeps',
  Hodl = 'hodl',
  TrustMeBro = 'trustMeBro',
  ThreePieceSuit = 'threePieceSuit',
  BuyHighSellLow = 'buyHighSellLow',
  ExitStrategy = 'exitStrategy',
  Ath = 'ath',
  Coastin = 'coastin',
  MarginCall = 'marginCall',
  BigShort = 'bigShort',
  HoldingTheBag = 'holdingTheBag',
  Boglehead = 'boglehead',
  CryptoBro = 'cryptoBro',
  TheVillages = 'theVillages',
  SeedRound = 'seedRound',
  Nineteen87 = 'nineteen87',
  Ramen = 'ramen',
  ToTheMoon = 'toTheMoon',
  Wagmi = 'wagmi',
  Ngmi = 'ngmi',
  BuyTheDip = 'buyTheDip',
  ThisIsFine = 'thisIsFine',
  DeadCatBounce = 'deadCatBounce',
  RugPull = 'rugPull',
  Whale = 'whale',
  LamboLoading = 'lamboLoading',
  TheSingularity = 'theSingularity',
  ZoomOutBro = 'zoomOutBro',
  BlackSwan = 'blackSwan',
  TulipMania = 'tulipMania',
  Nineteen29Vibes = 'nineteen29Vibes',
  DotComShuffle = 'dotComShuffle',
  BeanieBaby = 'beanieBaby',
  DebtSnowball = 'debtSnowball',
  SirThisIsAWendys = 'sirThisIsAWendys',
  Hopium = 'hopium',
  Copium = 'copium',
  BaristaFire = 'baristaFire',
  ThisTimeItsDifferent = 'thisTimeItsDifferent',
  Satoshi = 'satoshi',
}

export enum ThemeAppearance {
  Light = 'light',
  Dark = 'dark',
}

export enum ThemeVariantId {
  DefaultLight = 'default.light',
  DefaultDark = 'default.dark',
  MonokaiLight = 'monokai.light',
  MonokaiDark = 'monokai.dark',
  Synthwave84Light = 'synthwave84.light',
  Synthwave84Dark = 'synthwave84.dark',
  StayTheCourseLight = 'stayTheCourse.light',
  StayTheCourseDark = 'stayTheCourse.dark',
  HighContrastDark = 'highContrast.dark',
  PatagoniaVestLight = 'patagoniaVest.light',
  PatagoniaVestDark = 'patagoniaVest.dark',
  MoneyNeverSleepsLight = 'moneyNeverSleeps.light',
  MoneyNeverSleepsDark = 'moneyNeverSleeps.dark',
  HodlLight = 'hodl.light',
  HodlDark = 'hodl.dark',
  TrustMeBroLight = 'trustMeBro.light',
  TrustMeBroDark = 'trustMeBro.dark',
  ThreePieceSuitLight = 'threePieceSuit.light',
  ThreePieceSuitDark = 'threePieceSuit.dark',
  BuyHighSellLowLight = 'buyHighSellLow.light',
  BuyHighSellLowDark = 'buyHighSellLow.dark',
  ExitStrategyLight = 'exitStrategy.light',
  ExitStrategyDark = 'exitStrategy.dark',
  AthLight = 'ath.light',
  AthDark = 'ath.dark',
  CoastinLight = 'coastin.light',
  CoastinDark = 'coastin.dark',
  MarginCallLight = 'marginCall.light',
  MarginCallDark = 'marginCall.dark',
  BigShortLight = 'bigShort.light',
  BigShortDark = 'bigShort.dark',
  HoldingTheBagLight = 'holdingTheBag.light',
  HoldingTheBagDark = 'holdingTheBag.dark',
  BogleheadLight = 'boglehead.light',
  BogleheadDark = 'boglehead.dark',
  CryptoBroLight = 'cryptoBro.light',
  CryptoBroDark = 'cryptoBro.dark',
  TheVillagesLight = 'theVillages.light',
  TheVillagesDark = 'theVillages.dark',
  SeedRoundLight = 'seedRound.light',
  SeedRoundDark = 'seedRound.dark',
  Nineteen87Light = 'nineteen87.light',
  Nineteen87Dark = 'nineteen87.dark',
  RamenLight = 'ramen.light',
  RamenDark = 'ramen.dark',
  ToTheMoonLight = 'toTheMoon.light',
  ToTheMoonDark = 'toTheMoon.dark',
  WagmiLight = 'wagmi.light',
  WagmiDark = 'wagmi.dark',
  NgmiLight = 'ngmi.light',
  NgmiDark = 'ngmi.dark',
  BuyTheDipLight = 'buyTheDip.light',
  BuyTheDipDark = 'buyTheDip.dark',
  ThisIsFineLight = 'thisIsFine.light',
  ThisIsFineDark = 'thisIsFine.dark',
  DeadCatBounceLight = 'deadCatBounce.light',
  DeadCatBounceDark = 'deadCatBounce.dark',
  RugPullLight = 'rugPull.light',
  RugPullDark = 'rugPull.dark',
  WhaleLight = 'whale.light',
  WhaleDark = 'whale.dark',
  LamboLoadingLight = 'lamboLoading.light',
  LamboLoadingDark = 'lamboLoading.dark',
  TheSingularityLight = 'theSingularity.light',
  TheSingularityDark = 'theSingularity.dark',
  ZoomOutBroLight = 'zoomOutBro.light',
  ZoomOutBroDark = 'zoomOutBro.dark',
  BlackSwanLight = 'blackSwan.light',
  BlackSwanDark = 'blackSwan.dark',
  TulipManiaLight = 'tulipMania.light',
  TulipManiaDark = 'tulipMania.dark',
  Nineteen29VibesLight = 'nineteen29Vibes.light',
  Nineteen29VibesDark = 'nineteen29Vibes.dark',
  DotComShuffleLight = 'dotComShuffle.light',
  DotComShuffleDark = 'dotComShuffle.dark',
  BeanieBabyLight = 'beanieBaby.light',
  BeanieBabyDark = 'beanieBaby.dark',
  DebtSnowballLight = 'debtSnowball.light',
  DebtSnowballDark = 'debtSnowball.dark',
  SirThisIsAWendysLight = 'sirThisIsAWendys.light',
  SirThisIsAWendysDark = 'sirThisIsAWendys.dark',
  HopiumLight = 'hopium.light',
  HopiumDark = 'hopium.dark',
  CopiumLight = 'copium.light',
  CopiumDark = 'copium.dark',
  BaristaFireLight = 'baristaFire.light',
  BaristaFireDark = 'baristaFire.dark',
  ThisTimeItsDifferentLight = 'thisTimeItsDifferent.light',
  ThisTimeItsDifferentDark = 'thisTimeItsDifferent.dark',
  SatoshiLight = 'satoshi.light',
  SatoshiDark = 'satoshi.dark',
}
